---
gdb/gdb-7.4.1.tar.gz:
  object_id: rest/objects/4e4e78bca51e121204e4e86ee8e2c90504ee755cd736
  sha: 8aa908f01a6e572d356721297a741f622af6c407
  size: 27365650
ttf_dejavu/ttf_dejavu_2.30-2.tar.gz:
  object_id: rest/objects/4e4e78bca41e121004e4e7d517618f05052e5bb9b2f0
  sha: b12ca8740e9ad5897e2b2cda45c82ce5b358aaea
  size: 4496658
ruby/rubygems-1.7.2.tgz:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc05052e5c1b0272
  sha: d878ae52f40eb71e59708afc57303172f0327fad
  size: 245606
ruby/rubygems-1.8.24.tgz:
  object_id: rest/objects/4e4e78bca61e122004e4e8ec6b44b605052e5c4279f6
  sha: 30f27047e74f7943117736a0d3e224994fee0905
  size: 380101
ruby/ruby-1.8.7-p302.tar.bz2:
  object_id: rest/objects/4e4e78bca61e122204e4e98643d9ae05052e5c5d2194
  sha: d93bd2f1099f3473b496cda2422b27a8da2beb00
  size: 4184764
ruby/ruby-1.9.2-p180.tar.gz:
  object_id: rest/objects/4e4e78bca31e121004e4e7d514745f05052e5c7f1f5f
  sha: 6a482bc07239b37bcadf68dda63c65d20dc19ebe
  size: 11158935
ruby/ruby-1.8.7-p357.tar.bz2:
  object_id: rest/objects/4e4e78bca51e121204e4e86ee8e2c905052e5ca34b84
  sha: ba5ec0ab663976f00fb405be6cfef546bcf0e4e9
  size: 4208157
sqlite/sqlite-autoconf-3070500.tar.gz:
  object_id: rest/objects/4e4e78bca11e122204e4e98638b76305052e5db468ac
  sha: 4e1338497b8da50b84307191bb3418e9ec5715d7
  size: 1551070
node/node-v0.6.8.tar.gz:
  object_id: rest/objects/4e4e78bca21e121004e4e7d511f55305052e5dcb537f
  sha: c3f755b5dfd0de3f306d06573fa9433d845623dd
  size: 10488841
node/node-v0.4.12.tar.gz:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc05052e5de866c8
  sha: 1c6e34b90ad6b989658ee85e0d0cb16797b16460
  size: 12421469
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  object_id: rest/objects/4e4e78bca21e122004e4e8ec647a5405052e5e1e4667
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
  size: 169618
misc/tcl8-1.5.11rc1-src.tar:
  object_id: rest/objects/4e4e78bca61e122204e4e98643d9ae05052e5e38b84e
  sha: c9f5a466f1a791d499a5bc757771291a3c9af0d4
  size: 23408640
misc/expect5.45.tar:
  object_id: rest/objects/4e4e78bca11e121004e4e7d511f82105052e5e61a841
  sha: b8f475cf06a9c018ccd5cb82729a73b024d95d6d
  size: 2498560
memcached/memcached-linux-x86_64-1.4.13.tgz:
  object_id: rest/objects/4e4e78bca31e122004e4e8ec646e2105052e5ea760a0
  sha: 632afa4f19fc7741878ced4a239304b7be82f228
  size: 689699
gerrit/gerrit-2.2.2.1.war:
  object_id: rest/objects/4e4e78bca11e122204e4e98638b76305052e5ec25816
  sha: 1eed29ff6e4675b625464115fa31382ca7e4ceef
  size: 26152940
gerrit/gerrit-2.1.7.war:
  object_id: rest/objects/4e4e78bca21e121004e4e7d511f55305052e5eed09ee
  sha: 0ce0e274bb86cb07aceb5d36a94b0e595aad3392
  size: 18045975
gerrit/bcpg-jdk16-146.jar:
  object_id: rest/objects/4e4e78bca61e122004e4e8ec6b44b605052e5f33b4c9
  sha: 38c2557ffcc8f2a0d4326ccb86116986986775c9
  size: 174074
erlang/erlang.tgz:
  object_id: rest/objects/4e4e78bca61e122204e4e98643d9ae05052e5f5003e6
  sha: 83d210e45174dee0719ff31d039a1f92ad384dcf
  size: 54212730
mysql/server-5.1.54-rel12.5-188-Linux-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca51e121004e4e7d51906cd05052e5f89d4f8
  sha: a2d4694a12289a87bfb7fcef35c7b6a4284e5fc3
  size: 33824010
mysql/client-5.1.54-rel12.5-188-Linux-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca51e122004e4e8ec68407705052e5fd5a07f
  sha: 4a29cf608bcc16d7498a7ee27c88925ec52dadb8
  size: 4233644
java/jre_jdk_1.6.0_24-amd64.tar.gz:
  object_id: rest/objects/4e4e78bca51e122204e4e9863f28f305052e5ff5f035
  sha: e6f0c4bd020523716dd325f391c2e5d361115715
  size: 66504097
maven22/apache-maven-2.2.1-bin.tar.gz:
  object_id: rest/objects/4e4e78bca41e121204e4e86ee5392105052e60510ea6
  sha: 3ac63025e5860c4d856e172ab556d14b52f9b1f1
  size: 2840961
golang/go1.0.1.src.tar.gz:
  object_id: rest/objects/4e4e78bca21e122004e4e8ec647a5405052e606b164b
  sha: fc8a6d6725f7f2bf7c94685c5fd0880c9b7f67f6
  size: 9617092
zabbix_agent/bds-zabbix_0.1-39_all.deb:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076305052e608a4d8d
  sha: 540bd2ea1fcf465b5d2db983ac3e9f1f4ffb8bac
  size: 410458
go2xunit/go2xunit-0.1.0.tar.gz:
  object_id: rest/objects/4e4e78bca31e121004e4e7d514745f05052e60a3ff67
  sha: 624bfb8266120534dc30ab7194fc8a4260925ffc
  size: 21490
vblob/vblob.tgz:
  object_id: rest/objects/4e4e78bca51e122004e4e8ec68407705052e60d63454
  sha: 569b322aca26e7d9d1b05308a044bb9a53d38118
  size: 542347
nginx/lbase64.tar.gz:
  object_id: rest/objects/4e4e78bca11e122204e4e98638b76305052e60eb8647
  sha: 5692619dae780dbdf9edc994f9dcd7dce7b24646
  size: 2503
nginx/lua-openssl-0.1.1.tar.gz:
  object_id: rest/objects/4e4e78bca61e121004e4e7d51d950e05052e610348a1
  sha: 27f38b3f7d44f59690ed081f892891a35a5ebfaa
  size: 69253
nginx/headers-more-v0.15rc1.tgz:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc05052e611a4777
  sha: ba7bf757be8004d9dbffbe583396620cfcbed788
  size: 25490
nginx/nginx-lua.v0.3.1rc24.tar.gz:
  object_id: rest/objects/4e4e78bca61e122004e4e8ec6b44b605052e61328bf9
  sha: f06e390cc81f82b05a06451bf7b287b7d4fb1640
  size: 207185
nginx/nginx_upload_module-2.2.0.tar.gz:
  object_id: rest/objects/4e4e78bca21e122204e4e9863926b105052e6147968f
  sha: 93d6e83e613a0ce2ed057a434b344fa1b6609b47
  size: 25796
nginx/lua-cjson-1.0.3.tar.gz:
  object_id: rest/objects/4e4e78bca11e121004e4e7d511f82105052e615c92da
  sha: 7335961ff6619a7eae824e8cf9432100ca377476
  size: 31780
nginx/devel-kit-v0.2.17rc2.tar.gz:
  object_id: rest/objects/4e4e78bca31e121204e4e86ee3969205052e616e6f5c
  sha: 7eadfe53d674972c0f7f27d7b26eff95829bc0b2
  size: 64964
nginx/nginx-0.8.54.tar.gz:
  object_id: rest/objects/4e4e78bca51e122004e4e8ec68407705052e61837e06
  sha: 4d63c35b8974dba42cc62dd5046ae89df3528e34
  size: 650001
nginx/pcre-8.12.tar.gz:
  object_id: rest/objects/4e4e78bca11e122204e4e98638b76305052e6198252f
  sha: b3ab606864606c9f980045653554bf4a12cadde2
  size: 1316863
nginx/lua-5.1.4.tar.gz:
  object_id: rest/objects/4e4e78bca41e121004e4e7d517618f05052e61a9b4be
  sha: 2b11c8e60306efb7f0734b747588f57995493db7
  size: 216679
neo4j/neo4j.tgz:
  object_id: rest/objects/4e4e78bca61e121204e4e86eebe59105052e61c03c1d
  sha: 0bc828cddbf35495cc8e128115373b5397d4b525
  size: 46937414
couchdb/apache-couchdb-1.2.0.tar.gz:
  object_id: rest/objects/4e4e78bca21e122004e4e8ec647a5405052e62086ee6
  sha: 73c27b3e2b779dbc9e176965727c4b4b8a1053de
  size: 1172827
git/git-1.7.8.tar.gz:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d076305052e621d0af0
  sha: 7453e737e008f7319a5eca24a9ef3c5fb1f13398
  size: 3538330
elasticsearch/elasticsearch-0.19.4.tar.gz:
  object_id: rest/objects/4e4e78bca31e121004e4e7d514745f05052e623460a7
  sha: b76fc859887f262ed0420c2cd8cd93c5c2b17e63
  size: 13861592
postgres/postgres-9.0.3-1.amd64.tar.gz:
  object_id: rest/objects/4e4e78bca51e121204e4e86ee8e2c905052e625317df
  sha: e47ee9c841ecde4df121f44df282aeb3c50a48d2
  size: 16203511
postgres/postgresql-9.0.3.tar.gz:
  object_id: rest/objects/4e4e78bca31e122004e4e8ec646e2105052e6278934d
  sha: c8fb5d1d7930e78211e554bb5751183a8148d0ee
  size: 18335858
postgres/postgres-9.0.3-1.i386.tar.gz:
  object_id: rest/objects/4e4e78bca51e122204e4e9863f28f305052e629c1fae
  sha: b2bde31e720eb219bfdc9f1b784f985ecca2cbfb
  size: 15111387
jenkins/jenkins.war:
  object_id: rest/objects/4e4e78bca61e121004e4e7d51d950e05052e62bd632b
  sha: 5394a7876dc07df2f9d5ad2581df4a9569dc2cac
  size: 48777309
jenkins/plugins.tgz:
  object_id: rest/objects/4e4e78bca41e121004e4e7d517618f050c6a925a3360
  sha: 774981bd9c7d796d19c19faa5d88bf5658846649
  size: 37307569
redis/redis-2.6.2.tar.gz:
  object_id: rest/objects/4e4e78bca21e121004e4e7d511f553050cf0f2ccc2d9
  sha: 93e632ce88de07a9845aa5bcab67bdc16a7b574a
  size: 1000600
redis/redis-2.2.15.tar.gz:
  object_id: rest/objects/4e4e78bca21e121204e4e86ee151bc050cf0f2edd582
  sha: aa6758590363556e73f8d36bdfccb429011da331
  size: 456185
redis/redis-2.4.17.tar.gz:
  object_id: rest/objects/4e4e78bca21e122004e4e8ec647a54050cf0f30b05ff
  sha: 3d540531b3d7103a511d29661c2ae666dac60522
  size: 656155
services_jobs/services_ctl_jobs.tar.gz:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d0763050cf0f3221aab
  sha: 1a1cc01846a309a7221d1d15e187760c2cbfc372
  size: 22820
rabbitmq/rabbitmq-server-with-plugins-generic-unix-2.8.7.tar.gz:
  object_id: rest/objects/4e4e78bca51e121004e4e7d51906cd050cf0f334c027
  sha: 23db4c0fb8a43a0131f8e909c2821aaf85ea410b
  size: 2894762
rabbitmq/rabbitmq-server-with-plugins-generic-unix-2.4.1.tar.gz:
  object_id: rest/objects/4e4e78bca11e121204e4e86ee15294050cf0f34cb8fb
  sha: dfdfcf988a780af034c1568cae96e6a84e0c3668
  size: 1780598
mysql/mysql-service-5.1-patch.tgz:
  object_id: rest/objects/4e4e78bca31e122204e4e9863b1b74050cf0f457829d
  sha: 7b29fe2bcaee542079301fa8e7b25b3e15f28a98
  size: 3391
mysql/client-5.5.27-rel28.1-296.Linux.x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca21e121004e4e7d511f553050cf0f46d8a9d
  sha: e24b89fec6b9bb5380d8171e5fcad03dc86ca970
  size: 4556418
mysql/mysql-initdb-5.5.27-rel28.1-296.Linux.x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca61e121204e4e86eebe591050cf0f4867090
  sha: 13b525536fb903414691d470a5cae89dad64b004
  size: 422353
mysql/mysql-initdb-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca61e122004e4e8ec6b44b6050cf0f49cf0c3
  sha: 8122bcd96c3fa251ce6a4317570d01b4bf2b8420
  size: 53356
mysql/mysql-service-5.5-patch.tgz:
  object_id: rest/objects/4e4e78bca61e122204e4e98643d9ae050cf0f4b2be74
  sha: 098815a425dc13dda2072130c7ccb7506629a590
  size: 3349
mysql/client-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca51e121004e4e7d51906cd050cf0f4ca5d41
  sha: 6e5a17195831688a5f14f20aa5d9cd5d5f4164db
  size: 4105211
mysql/server-5.1.62-rel13.3-435-Linux-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca51e121204e4e86ee8e2c9050cf0f4e53ce9
  sha: 2bfd575545fe78729c56bb832aa69d8d9fc8630d
  size: 34179263
mysql/server-5.5.27-rel28.1-296.Linux.x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca31e122004e4e8ec646e21050cf0f5225f7c
  sha: 2509e80864c20c381ad263ccc085e0794ef8307e
  size: 59482086
postgresql/postgresql-9.0-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca51e122204e4e9863f28f3050cf0f5658eb6
  sha: 1c777413ce355ebf79c5786e7dbc5a060883986f
  size: 17345516
postgresql/postgresql-initdb-9.1-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca61e121204e4e86eebe591050cf0f58460ca
  sha: c51a45f5a6011a6bb22407c164ea9b77f77cddad
  size: 3911161
postgresql/postgresql-initdb-9.0-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca41e122004e4e8ec65f67f050cf0f59aa59c
  sha: 181900c6346f718ccd7cfbb8813e7c00f760bc55
  size: 3467921
postgresql/postgresql-9.1-x86_64.tar.gz:
  object_id: rest/objects/4e4e78bca41e122204e4e9863d0763050cf0f5b82ffc
  sha: d6c44760c1e5eb055b6ac4a8080b061d6d04fa3c
  size: 26556736
mongodb/mongodb-linux-x86_64-1.8.5.tgz:
  object_id: rest/objects/4e4e78bca51e121004e4e7d51906cd050cf0f5e67462
  sha: 235605f306b66584d2aa00b61d45b4605f87867e
  size: 28156593
mongodb/mongodb-linux-i686-2.0.6.tgz:
  object_id: rest/objects/4e4e78bca11e121204e4e86ee15294050cf0f615f62e
  sha: b46ea3927388532ad1d5027fdaed1d37d6c00fa6
  size: 38296132
mongodb/mongodb-linux-x86_64-2.0.6.tgz:
  object_id: rest/objects/4e4e78bca31e122004e4e8ec646e21050cf0f643b0e3
  sha: 4ba3f2849653cb8f63410f9d901a3388b291d879
  size: 38572579
mongodb/mongodb-linux-i686-2.2.1.tgz:
  object_id: rest/objects/4e4e78bca31e122204e4e9863b1b74050cf0f672fbc0
  sha: f06a37c29504f6f92d8a59acf49d86512bc5a2ae
  size: 54552128
mongodb/mongodb-linux-x86_64-2.2.1.tgz:
  object_id: rest/objects/4e4e78bca41e121004e4e7d517618f050cf0f6ae9493
  sha: 118dd2b5b049b10df2c6cdc9e92ec8f90cf508c0
  size: 55748872
mongodb/mongodb-linux-i686-1.8.5.tgz:
  object_id: rest/objects/4e4e78bca61e121204e4e86eebe591050cf0f6ec0473
  sha: f75d2fd7a4e0a7116ea612bb62b710a1ba0fa2b2
  size: 27749757
erlang/otp_src_R14B01.tar.gz:
  object_id: rest/objects/4e4e78bca41e122004e4e8ec65f67f050cf0f723bf4e
  sha: f0e0529ed73587c2c4aaeb3f3a01555bd6cfe05c
  size: 64846537
services_warden_rootfs/services_warden_rootfs.tgz:
  object_id: rest/objects/4e4e78bca61e121204e4e86eebe591050d827b67a57e
  sha: b2654612b19995a751c6ae31034adbbcd34bbfd6
  size: 245593923
gerrit/gerrit-2.5.1.war:
  object_id: rest/objects/4e4e78bca41e121204e4e86ee53921050e69ca838504
  sha: 3ef6350153919524cf9d61bf9b1ac404295e4279
  size: 24675899
gerrit/replication-1.0.jar:
  object_id: rest/objects/4e4e78bca61e121204e4e86eebe591050d418ec37096
  sha: d0c74090168d5c8c4f5c68a8a92d69015523ce44
  size: 47824
